<template>
  <div class="w-full h-screen">
    <div class="loadingio-spinner-pulse-5m6l2ibdmke">
      <div class="ldio-92ewszbjy5">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Loader"
}
</script>

<style scoped>
@keyframes ldio-92ewszbjy5-1 {
  0% {
    top: -4.02px;
    height: 209.03999999999996px
  }
  50% {
    top: 48.239999999999995px;
    height: 104.51999999999998px
  }
  100% {
    top: 48.239999999999995px;
    height: 104.51999999999998px
  }
}

@keyframes ldio-92ewszbjy5-2 {
  0% {
    top: 9.044999999999998px;
    height: 182.90999999999997px
  }
  50% {
    top: 48.239999999999995px;
    height: 104.51999999999998px
  }
  100% {
    top: 48.239999999999995px;
    height: 104.51999999999998px
  }
}

@keyframes ldio-92ewszbjy5-3 {
  0% {
    top: 22.11px;
    height: 156.77999999999997px
  }
  50% {
    top: 48.239999999999995px;
    height: 104.51999999999998px
  }
  100% {
    top: 48.239999999999995px;
    height: 104.51999999999998px
  }
}

.ldio-92ewszbjy5 div {
  position: absolute;
  width: 24.119999999999997px
}

.ldio-92ewszbjy5 div:nth-child(1) {
  left: 38.19px;
  background: #0867b2;
  animation: ldio-92ewszbjy5-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s
}

.ldio-92ewszbjy5 div:nth-child(2) {
  left: 88.44px;
  background: #0867b2;
  animation: ldio-92ewszbjy5-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s
}

.ldio-92ewszbjy5 div:nth-child(3) {
  left: 138.69px;
  background: #0867b2;
  animation: ldio-92ewszbjy5-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds
}

.loadingio-spinner-pulse-5m6l2ibdmke {
  position: relative;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 201px;
  height: 201px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}

.ldio-92ewszbjy5 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-92ewszbjy5 div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>